# Generated by Django 3.2.18 on 2023-02-23 12:51

import core.models.recipe
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230117_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.recipe.recipe_image_file_path),
        ),
    ]
